CampingLaRustique/CampingLaRustique/Models/Camping.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CampingLaRustique.Models
{
    public class Camping
    {
        [Key]
        public int PlekID { get; set; }

        public string Type { get; set; }

        public string Oppervlakte { get; set; }

        public bool GratisDouche { get; set; }

        public bool Huisdieren { get; set; }

        public bool Elektriciteit { get; set; }

        public string Ligging { get; set; }

        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public Decimal Prijs { get; set; }
    }
}

CampingLaRustique/CampingLaRustique/Models/CampingViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace CampingLaRustique.Models
{
    public class CampingViewModel
    {
        public List<Camping> campings { get; set; }
        public SelectList Types { get; set; }
        public string Typess { get; set; }
        public string SearchString { get; set; }
    }
}

CampingLaRustique/CampingLaRustique/Controllers/CampingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CampingLaRustique.Data;
using CampingLaRustique.Models;

namespace CampingLaRustique.Controllers
{
    public class CampingController : Controller
    {
        private readonly KlantenContext _context;

        public CampingController(KlantenContext context)
        {
            _context = context;
        }

        // GET: Camping
        public async Task<IActionResult> Index(string Typess, string searchString)
        {
            IQueryable<string> campingQuery = from m in _context.Camping
                                            orderby m.Type
                                            select m.Type;

            var campings = from m in _context.Camping
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                campings = campings.Where(s => s.Ligging.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(Typess))
            {
                campings = campings.Where(x => x.Type == Typess);
            }

            var typeVM = new CampingViewModel
            {
                Types = new SelectList(await campingQuery.Distinct().ToListAsync()),
                campings = await campings.ToListAsync()
            };

            return View(typeVM);
        }

        // GET: Camping/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var camping = await _context.Camping
                .FirstOrDefaultAsync(m => m.PlekID == id);
            if (camping == null)
            {
                return NotFound();
            }

            return View(camping);
        }

        // GET: Camping/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Camping/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlekID,Type,Oppervlakte,GratisDouche,Huisdieren,Elektriciteit,Ligging")] Camping camping)
        {
            if (ModelState.IsValid)

            {
                _context.Add(camping);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(camping);
        }

        // GET: Camping/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var camping = await _context.Camping.FindAsync(id);
            if (camping == null)
            {
                return NotFound();
            }
            return View(camping);
        }

        // POST: Camping/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PlekID,Type,Oppervlakte,GratisDouche,Huisdieren,Elektriciteit,Ligging")] Camping camping)
        {
            if (id != camping.PlekID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(camping);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CampingExists(camping.PlekID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(camping);
        }

        // GET: Camping/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var camping = await _context.Camping
                .FirstOrDefaultAsync(m => m.PlekID == id);
            if (camping == null)
            {
                return NotFound();
            }

            return View(camping);
        }

        // POST: Camping/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var camping = await _context.Camping.FindAsync(id);
            _context.Camping.Remove(camping);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CampingExists(int id)
        {
            return _context.Camping.Any(e => e.PlekID == id);
        }
    }
}

CampingLaRustique/CampingLaRustique/Controllers/KlantenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CampingLaRustique.Data;
using CampingLaRustique.Models;

namespace CampingLaRustique.Controllers
{
    public class KlantenController : Controller
    {
        private readonly KlantenContext _context;

        public KlantenController(KlantenContext context)
        {
            _context = context;
        }

        // GET: Klantens
        public async Task<IActionResult> Index(string PostcodeNummer, string searchString)
        {

            var Klanten = from m in _context.Klant
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                Klanten = Klanten.Where(s => s.Achternaam.Contains(searchString));
            }

            return View(await Klanten.ToListAsync());

        }

        // GET: Klantens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klanten = await _context.Klant
                .FirstOrDefaultAsync(m => m.KlantID == id);
            if (klanten == null)
            {
                return NotFound();
            }

            return View(klanten);
        }

        // GET: Klantens/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Klantens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("KlantID,Voornaam,Achternaam,Woonplaats,Postcode,Telefoon")] Klanten klanten)
        {
            if (ModelState.IsValid)
            {
                _context.Add(klanten);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(klanten);
        }

        // GET: Klantens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klanten = await _context.Klant.FindAsync(id);
            if (klanten == null)
            {
                return NotFound();
            }
            return View(klanten);
        }

        // POST: Klantens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("KlantID,Voornaam,Achternaam,Woonplaats,Postcode,Telefoon")] Klanten klanten)
        {
            if (id != klanten.KlantID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(klanten);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KlantenExists(klanten.KlantID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(klanten);
        }

        // GET: Klantens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klanten = await _context.Klant
                .FirstOrDefaultAsync(m => m.KlantID == id);
            if (klanten == null)
            {
                return NotFound();
            }

            return View(klanten);
        }

        // POST: Klantens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var klanten = await _context.Klant.FindAsync(id);
            _context.Klant.Remove(klanten);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KlantenExists(int id)
        {
            return _context.Klant.Any(e => e.KlantID == id);
        }
    }
}

CampingLaRustique/CampingLaRustique/Views/Camping/Create.cshtml
@model CampingLaRustique.Models.Camping

@{
    ViewData["Title"] = "Create";
}

<h1>Kampeerplek toevoegen</h1>

<h4></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Oppervlakte" class="control-label"></label>
                <input asp-for="Oppervlakte" class="form-control" />
                <span asp-validation-for="Oppervlakte" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="GratisDouche" /> @Html.DisplayNameFor(model => model.GratisDouche)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Huisdieren" /> @Html.DisplayNameFor(model => model.Huisdieren)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Elektriciteit" /> @Html.DisplayNameFor(model => model.Elektriciteit)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Ligging" class="control-label"></label>
                <input asp-for="Ligging" class="form-control" />
                <span asp-validation-for="Ligging" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Toevoegen" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar kampeerplekken</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CampingLaRustique/CampingLaRustique/Views/Camping/Delete.cshtml
@model CampingLaRustique.Models.Camping

@{
    ViewData["Title"] = "Delete";
}

<h1>Verwijderen</h1>

<h3>Weet u zeker dat u deze kampeerplek wilt verwijderen?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Oppervlakte)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Oppervlakte)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GratisDouche)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GratisDouche)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Huisdieren)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Huisdieren)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Elektriciteit)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Elektriciteit)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ligging)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ligging)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PlekID" />
        <input type="submit" value="Verwijderen" class="btn btn-danger" /> |
        <a asp-action="Index">Terug naar kampeerplekken</a>
    </form>
</div>

CampingLaRustique/CampingLaRustique/Views/Camping/Details.cshtml
@model CampingLaRustique.Models.Camping

@{
    ViewData["Title"] = "Details";
}

<h1>Kampeerplek gegevens</h1>

<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Oppervlakte)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Oppervlakte)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GratisDouche)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GratisDouche)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Huisdieren)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Huisdieren)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Elektriciteit)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Elektriciteit)
        </dd>
        <dt cl
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ligging)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ligging)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PlekID">Aanpassen</a> |
    <a asp-action="Index">Terug naar kampeerplekken</a>
</div>

CampingLaRustique/CampingLaRustique/Views/Camping/Edit.cshtml
@model CampingLaRustique.Models.Camping

@{
    ViewData["Title"] = "Edit";
}

<h1>Kampeerplek bijwerken</h1>

<h4></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PlekID" />
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Oppervlakte" class="control-label"></label>
                <input asp-for="Oppervlakte" class="form-control" />
                <span asp-validation-for="Oppervlakte" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="GratisDouche" /> @Html.DisplayNameFor(model => model.GratisDouche)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="GratisDouche" /> @Html.DisplayNameFor(model => model.Huisdieren)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="GratisDouche" /> @Html.DisplayNameFor(model => model.Elektriciteit)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Ligging" class="control-label"></label>
                <input asp-for="Ligging" class="form-control" />
                <span asp-validation-for="Ligging" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Opslaan" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar kampeerplekken</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CampingLaRustique/CampingLaRustique/Views/Camping/Index.cshtml
@model CampingLaRustique.Models.CampingViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Kampeerplekken</h1>

<p>
    <a asp-action="Create">Voeg nieuwe kampeerplek toe</a>
</p>

<form asp-controller="Camping" asp-action="Index" method="get">
    <p>
       Filter de types: <select asp-for="Typess" asp-items="Model.Types">
            <option value="">All</option>
        </select>

        Zoek de ligging: <input type="text" name="SearchString" />
        <input type="submit" value="Zoeken" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.campings[0].PlekID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.campings[0].Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.campings[0].Oppervlakte)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.campings[0].GratisDouche)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.campings[0].Huisdieren)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.campings[0].Elektriciteit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.campings[0].Ligging)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.campings[0].Prijs)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.campings) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PlekID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Oppervlakte)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GratisDouche)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Huisdieren)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Elektriciteit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ligging)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prijs)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PlekID">Aanpassen</a> |
                <a asp-action="Details" asp-route-id="@item.PlekID">Gegevens</a> |
                <a asp-action="Delete" asp-route-id="@item.PlekID">Verwijderen</a>
            </td>
        </tr>
}
    </tbody>
</table>

<p>
    <a asp-controller="Klanten" asp-action="Index">Naar de klantenlijst</a>
</p>