CampingLaRustique/CampingLaRustique/Models/Reservering.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading.Tasks;

namespace CampingLaRustique.Models
{
    public class Reservering
    {
        [Key]
        public int Reserveringsnummer { get; set; }

        public int KlantID { get; set; }

        public int PlekID { get; set; }

        [DataType(DataType.Date)]
        public DateTime Datum { get; set; }



        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public Decimal Prijs { get; set; }

        public bool Betaald { get; set; }

    }
}

CampingLaRustique/CampingLaRustique/Models/ReserveringViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace CampingLaRustique.Models
{
    public class ReserveringViewModel
    {
        public List<Klanten> klanten { get; set; }
        public List<Camping> campings { get; set; }
        public List<Reservering> reserverings { get; set; }

        public int IsSelected { get; set; }
    }
}

CampingLaRustique/CampingLaRustique/Controllers/ReserveringController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CampingLaRustique.Data;
using CampingLaRustique.Models;
using Microsoft.AspNetCore.Http;
using System.Globalization;

namespace CampingLaRustique.Controllers
{
    public class ReserveringController : Controller
    {
        private readonly KlantenContext _context;

        public ReserveringController(KlantenContext context)
        {
            _context = context;
        }

        // GET: Reservering
        public async Task<IActionResult> Index()
        {
            return View(await _context.Reservering.ToListAsync());
        }


        // GET: Reservering/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservering = await _context.Reservering
                .FirstOrDefaultAsync(m => m.Reserveringsnummer == id);
            if (reservering == null)
            {
                return NotFound();
            }

            return View(reservering);
        }

        // GET: Reservering/Create
        public IActionResult Create()
        {


            return View();
        }

        // GET: Reservering/Create
        public async Task<IActionResult> Create2()
        {
            //var campings = from m in _context.Camping
            //                select m;

            DateTime dt;
            Reservering rsv = new Reservering();
            DateTime.TryParse(HttpContext.Session.GetString("Datum"), out dt);


            var ReserveringIDs = _context.Reservering.Where(y => y.Datum == dt).Select(x => x.PlekID).ToList();
            var PlekID = _context.Camping.Select(x => x.PlekID).ToList().Except(ReserveringIDs);
            var CampingsList = _context.Camping.Select(x => x).ToList();

            var result = new List<Camping>();
            foreach (var v in CampingsList)
            {
                if (PlekID.Contains(v.PlekID))
                    result.Add(v);
            }
            
            var ReserveringVM = new ReserveringViewModel
            {
                campings = result
            };

            return View(ReserveringVM);
        }

        // GET: Reservering/Create
        public async Task<IActionResult> Create3()
        {
            var klanten = from m in _context.Klant
                          select m;

            var ReserveringVM = new ReserveringViewModel
            {
                klanten = await klanten.ToListAsync()
            };

            return View(ReserveringVM);
        }


        // Get Create4
        public async Task<IActionResult> Create4(ReserveringViewModel model)
        {
            var campings = from m in _context.Camping
                           select m;
            var klanten = from m in _context.Klant
                          select m;

            var ReserveringVM = new ReserveringViewModel
            {
                klanten = await klanten.ToListAsync(),
                campings = await campings.ToListAsync(),
                //reserverings = await reservings.ToListAsync()
            };

            DateTime dt;
            DateTime.TryParse(HttpContext.Session.GetString("Datum"), out dt);
            Decimal pr;
            Decimal.TryParse(HttpContext.Session.GetString("Prijs"), out pr);

            List<Reservering> ReserveringList = new List<Reservering>();

            ReserveringList.Add(new Reservering()
            {
                Datum = dt,
                PlekID = (int)HttpContext.Session.GetInt32("PlekId"),
                KlantID = (int)HttpContext.Session.GetInt32("KlantId"),
                Prijs = pr
            });

            ReserveringVM.reserverings = ReserveringList;

            return View(ReserveringVM);

        }

        // POST: Reservering/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Reserveringsnummer,KlantID,PlekID,Datum,Prijs,Betaald")] Reservering model, string BtnVolgende)
        {
            if (BtnVolgende != null)
            {
                if (ModelState.IsValid)
                {
                    HttpContext.Session.SetString("Datum", model.Datum.ToString("dd-MM-yyyy"));
                    //var ReserveringVM = new ReserveringViewModel();
                    // ReserveringVM.reserverings[0].Datum = model.Datum;


                    return Redirect("Create2");
                }
                return View();
            }
            return View();
        }

        //Create2
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create2([Bind("Reserveringsnummer,KlantID,PlekID,Datum,Prijs,Betaald")] string BtnVorige, string BtnVolgende, ReserveringViewModel model)
        {
            DateTime dt;
            Reservering rsv = new Reservering();
            DateTime.TryParse(HttpContext.Session.GetString("Datum"), out dt);
            rsv.Datum = dt;

            var camping = await _context.Camping.FindAsync(model.IsSelected);

            if (BtnVorige != null)
            {
                return View("Create", rsv);
            }

            if (BtnVolgende != null)
            {
                if (ModelState.IsValid)
                {
                    HttpContext.Session.SetInt32("PlekId", model.IsSelected);
                    HttpContext.Session.SetString("Prijs", camping.Prijs.ToString());

                    return Redirect("Create3");
                }
                return View();
            }
            return Redirect("Create3");
        }

        //Create3
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create3([Bind("Reserveringsnummer,KlantID,PlekID,Datum,Prijs,Betaald")] string BtnVorige, string BtnVolgende, ReserveringViewModel model)
        {
            if (BtnVorige != null)
            {
                return View("Create2");
            }

            if (BtnVolgende != null)
            {
                if (ModelState.IsValid)
                {
                    HttpContext.Session.SetInt32("KlantId", model.IsSelected);
                    return Redirect("Create4");
                }
                return View();
            }
            return Redirect("Create4");
        }


        //Create4
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create4([Bind("Reserveringsnummer,KlantID,PlekID,Datum,Prijs,Betaald")] ReserveringViewModel model, string BtnVorige, string BtnOpslaan)
        {

            if (BtnOpslaan != null)
            {
                if (ModelState.IsValid)
                {
                    DateTime dt;
                    Reservering rsv = new Reservering();
                    DateTime.TryParse(HttpContext.Session.GetString("Datum"), out dt);
                    Decimal pr;
                    Decimal.TryParse(HttpContext.Session.GetString("Prijs"), out pr);

                    rsv.Datum = dt;
                    rsv.PlekID = (int)HttpContext.Session.GetInt32("PlekId");
                    rsv.KlantID = (int)HttpContext.Session.GetInt32("KlantId");
                    rsv.Prijs = pr;
                    _context.Add(rsv);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                    // return Redirect("Index");
                }
                return View("Index");
            }
            return View("Index");
        }




        // GET: Reservering/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservering = await _context.Reservering.FindAsync(id);
            if (reservering == null)
            {
                return NotFound();
            }
            return View(reservering);
        }

        // POST: Reservering/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Reserveringsnummer,KlantID,PlekID,Datum,Prijs,Betaald")] Reservering reservering)
        {
            if (id != reservering.Reserveringsnummer)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reservering);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReserveringExists(reservering.Reserveringsnummer))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reservering);
        }

        // GET: Reservering/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservering = await _context.Reservering
                .FirstOrDefaultAsync(m => m.Reserveringsnummer == id);
            if (reservering == null)
            {
                return NotFound();
            }

            return View(reservering);
        }

CampingLaRustique/CampingLaRustique/Views/Reservering/Create.cshtml
@model CampingLaRustique.Models.Reservering

@{
    ViewData["Title"] = "Create";
}
<h1>Reservering plaatsen</h1>

<h4>Kies een datum</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Datum" class="control-label"></label>
                <input asp-for="Datum" class="form-control" />
                <span asp-validation-for="Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" name="BtnVolgende" value='Volgende' class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

    <div>
        <a asp-action="Index">Terug naar reserveringen</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

CampingLaRustique/CampingLaRustique/Views/Reservering/Create2.cshtml
@model CampingLaRustique.Models.ReserveringViewModel
@{
    ViewData["Title"] = "Create2";
}

<h1>Reservering plaatsen</h1>

<h4>Selecteer een plek</h4>
<hr />
<div class="row">
    <!--   -->
    <form asp-controller="Reservering" asp-action="Create2" method="post">
            <!-- <div asp-validation-summary="ModelOnly" class="text-danger"></div> -->
        <div class="form-group">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.campings[0].PlekID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.campings[0].Type)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.campings[0].Oppervlakte)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.campings[0].GratisDouche)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.campings[0].Huisdieren)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.campings[0].Elektriciteit)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.campings[0].Ligging)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.campings[0].Prijs)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.campings)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlekID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Type)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Oppervlakte)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GratisDouche)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Huisdieren)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Elektriciteit)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ligging)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Prijs)
                        </td>
                        <td>
                            @Html.RadioButtonFor(model => model.IsSelected, item.PlekID, new { id = item.PlekID })
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
            <div class="form-group">
                <input type="submit" name="BtnVorige" value='Vorige' class="btn btn-primary" />
                <input type="submit" name="BtnVolgende" value='Volgende' class="btn btn-primary" />
            </div>
        </form>
</div>




<div>
    <div class="col-md-4">
        <a asp-action="Index">Terug naar reserveringen</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CampingLaRustique/CampingLaRustique/Views/Reservering/Create3.cshtml
@model CampingLaRustique.Models.ReserveringViewModel
@{
    ViewData["Title"] = "Create3";
}

<h1>Reservering plaatsen</h1>

<h4>Selecteer een klant</h4>
<hr />
<div class="row">
    <!--   -->
    <form asp-controller="Reservering" asp-action="Create3" method="post">
        <!-- <div asp-validation-summary="ModelOnly" class="text-danger"></div> -->
        <div class="form-group">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.klanten[0].KlantID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.klanten[0].Voornaam)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.klanten[0].Achternaam)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.klanten[0].Woonplaats)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.klanten[0].Postcode)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.klanten[0].Telefoon)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.klanten)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.KlantID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Voornaam)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Achternaam)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Woonplaats)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Postcode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Telefoon)
                            </td>
                            <td>
                                @Html.RadioButtonFor(model => model.IsSelected, item.KlantID, new { id = item.KlantID })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="form-group">
            <input type="submit" name="BtnVorige" value='Vorige' class="btn btn-primary" />
            <input type="submit" name="BtnVolgende" value='Volgende' class="btn btn-primary" />
        </div>

    </form>
</div>



<div>
    <div class="col-md-4">
        <a asp-action="Index">Terug naar reserveringen</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CampingLaRustique/CampingLaRustique/Views/Reservering/Create4.cshtml
@model CampingLaRustique.Models.ReserveringViewModel


@{
    ViewData["Title"] = "Bevestigen";
}

<div class="text-center">

    <h1 class="display-4">Bevestig reservering</h1>
    <p>De details van uw reservering</p>

</div>

<form asp-controller="Reservering" asp-action="Create4" method="post">
    <div>
        <h4>Reservering</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.reserverings[0].KlantID)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.reserverings[0].KlantID)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.reserverings[0].PlekID)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.reserverings[0].PlekID)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.reserverings[0].Datum)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.reserverings[0].Datum)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.reserverings[0].Prijs)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.reserverings[0].Prijs)
            </dd>
        </dl>
    </div>



    <div class="form-group">
        <input type="submit" name="BtnOpslaan" value='Opslaan' class="btn btn-primary" />
    </div>
</form>

CampingLaRustique/CampingLaRustique/Views/Reservering/Delete.cshtml
@model CampingLaRustique.Models.Reservering

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reservering</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KlantID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KlantID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlekID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlekID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prijs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prijs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Betaald)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Betaald)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Reserveringsnummer" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CampingLaRustique/CampingLaRustique/Views/Reservering/Details.cshtml
@model CampingLaRustique.Models.Reservering

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Reservering</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KlantID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KlantID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlekID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlekID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prijs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prijs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Betaald)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Betaald)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Reserveringsnummer">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CampingLaRustique/CampingLaRustique/Views/Reservering/Edit.cshtml
@model CampingLaRustique.Models.Reservering

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Reservering</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Reserveringsnummer" />
            <div class="form-group">
                <label asp-for="KlantID" class="control-label"></label>
                <input asp-for="KlantID" class="form-control" />
                <span asp-validation-for="KlantID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlekID" class="control-label"></label>
                <input asp-for="PlekID" class="form-control" />
                <span asp-validation-for="PlekID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datum" class="control-label"></label>
                <input asp-for="Datum" class="form-control" />
                <span asp-validation-for="Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prijs" class="control-label"></label>
                <input asp-for="Prijs" class="form-control" />
                <span asp-validation-for="Prijs" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Betaald" /> @Html.DisplayNameFor(model => model.Betaald)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CampingLaRustique/CampingLaRustique/Views/Reservering/Index.cshtml
@model IEnumerable<CampingLaRustique.Models.Reservering>

@{
    ViewData["Title"] = "Index";
}

<h1>Reserveringen</h1>

<p>
    <a asp-action="Create">Voeg reservering toe</a>
</p>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.KlantID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlekID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Datum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prijs)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Betaald)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KlantID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlekID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Datum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prijs)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Betaald)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Reserveringsnummer">Aanpassen</a> |
                    <a asp-action="Details" asp-route-id="@item.Reserveringsnummer">Gegevens</a> |
                    <a asp-action="Delete" asp-route-id="@item.Reserveringsnummer">Verwijderen</a>
                </td>
            </tr>
        }
    </tbody>
</table>